import { getBlankProjectInput, type IntakeForm } from "@/lib/buildwise";

function fixture(values: Partial<IntakeForm>): IntakeForm {
  return { ...getBlankProjectInput(), executionsPerMonth: 1000, typicalInputValue: 500, highInputValue: 1200, typicalOutputValue: 200, sampleInput: "Representative input", businessOutcome: "Improve measurable quality and cycle time.", ...values };
}

export const scenarioFixtures = {
  customerSupport: fixture({
    projectName: "Customer-support triage",
    industry: "Technology",
    problemStatement: "Triage support contacts, retrieve policy evidence, and draft grounded replies.",
    targetUsers: "Support agents",
    executionsPerMonth: 100000,
    averageConversationTurns: 6,
    conversationHistory: true,
    retrievedPassages: 5,
    tokensPerPassage: 260,
    humanReview: true,
    qualitySensitivity: "high",
    builderPreference: "pro-code",
  }),
  pharmaceutical: fixture({
    projectName: "Pharmaceutical adverse-event intake",
    industry: "Pharmaceuticals",
    problemStatement: "Capture adverse-event reports with citations and specialist review without autonomous reportability decisions.",
    targetUsers: "Pharmacovigilance specialists",
    executionsPerMonth: 12000,
    qualitySensitivity: "critical",
    dataSensitivity: "regulated",
    citations: true,
    humanReview: true,
    retrievedPassages: 8,
    tokensPerPassage: 400,
  }),
  accountsPayable: fixture({
    projectName: "Accounts-payable invoice processing",
    industry: "Finance",
    problemStatement: "Use OCR to extract invoices then deterministically validate supplier, purchase order, tax, and totals.",
    targetUsers: "Accounts payable analysts",
    executionsPerMonth: 80000,
    typicalInputUnit: "pages",
    typicalInputValue: 3,
    highInputUnit: "pages",
    highInputValue: 12,
    attachedDocuments: 1,
    structuredOutput: true,
    builderPreference: "low-code",
  }),
  industrialMaintenance: fixture({
    projectName: "Industrial maintenance diagnosis",
    industry: "Manufacturing",
    problemStatement: "Combine sensor events and maintenance history into safety-aware diagnostic recommendations.",
    targetUsers: "Maintenance technicians",
    executionsPerMonth: 6000,
    qualitySensitivity: "critical",
    humanReview: true,
    sampleInput: "Pump vibration rose above the operating envelope after a bearing replacement.",
  }),
  accountResearch: fixture({
    projectName: "Enterprise account-research assistant",
    industry: "B2B",
    problemStatement: "Synthesize current account initiatives, buying signals, risks, and stakeholders from cited fresh sources.",
    targetUsers: "Enterprise account teams",
    executionsPerMonth: 24000,
    typicalInputUnit: "tokens",
    typicalInputValue: 12000,
    highInputUnit: "tokens",
    highInputValue: 48000,
    retrievedPassages: 16,
    tokensPerPassage: 450,
    citations: true,
    builderPreference: "architecture",
  }),
  payrollTax: fixture({
    projectName: "Payroll tax calculation",
    industry: "Payroll",
    problemStatement: "Calculate payroll tax and withholding from versioned statutory rules with exact arithmetic.",
    targetUsers: "Payroll specialists",
    executionsPerMonth: 150000,
    qualitySensitivity: "critical",
    dataSensitivity: "regulated",
    structuredOutput: true,
    humanReview: true,
    builderPreference: "pro-code",
  }),
} satisfies Record<string, IntakeForm>;
